Repository goaop/parser-reflection, pull requests merged in 2019-12, with the labels that each got.

#96 getNamespaceAliases() behavior changed in 2.0
  src/ReflectionFileNamespace.php
  tests/ReflectionFileNamespaceTest.php
  tests/Stub/FileWithNamespaces.php
Labels: Bug

#98 PHP7.4 compatibility fix.
  src/ReflectionMethod.php
Labels: Bug, PHP7.4

#97 Added support for ReflectionClassConstant
  .travis.yml
  README.md
  composer.json
  src/ReflectionClassConstant.php
  src/ReflectionEngine.php
  src/Traits/ReflectionClassLikeTrait.php
  src/bootstrap.php
  src/polyfill.php
  tests/ReflectionClassConstantTest.php
  tests/ReflectionClassTest.php
  tests/ReflectionTypeTest.php
  tests/Stub/FileWithClasses71.php
Labels: PHP7.1, PHP7.2, enhancement
